In [175]:
import numpy as np
import pandas as pd

### Step 1: Computing the d-dimensional mean vectors

In [176]:
np.set_printoptions(precision=4)

X = np.array([[2, 4], [3, 5], [3, 2], [5, 3]])
y = np.array([1, 1, 2, 2])

print(np.array(X).shape)
print(np.array(y).shape)
print()

mean_vectors = []
for cl in range(1,3):
    mean_vectors.append(np.mean(X[y==cl], axis=0))
    print('Mean Vector class %s: %s\n' %(cl, mean_vectors[cl-1]))


(4, 2)
(4,)

Mean Vector class 1: [2.5 4.5]

Mean Vector class 2: [4.  2.5]



### Step 2: Computing the Scatter Matrices

#### 2.1 Within-class scatter matrix SW

In [177]:
S_W = np.zeros((2,2))
for cl,mv in zip(range(1,3), mean_vectors):
    class_sc_mat = np.zeros((2,2))                  # scatter matrix for every class
    for row in X[y == cl]:
        row, mv = row.reshape(2,1), mv.reshape(2,1) # make column vectors
        class_sc_mat += (row-mv).dot((row-mv).T)
    S_W += class_sc_mat                             # sum class scatter matrices
print('within-class Scatter Matrix:\n', S_W)

within-class Scatter Matrix:
 [[2.5 1.5]
 [1.5 1. ]]


#### 2.2 Between-class scatter matrix SB

In [178]:
overall_mean = np.mean(X, axis=0)

S_B = np.zeros((2,2))
for i,mean_vec in enumerate(mean_vectors):  
    n = X[y==i+1,:].shape[0]
    mean_vec = mean_vec.reshape(2,1) # make column vector
    overall_mean = overall_mean.reshape(2,1) # make column vector
    S_B += n * (mean_vec - overall_mean).dot((mean_vec - overall_mean).T)

print('between-class Scatter Matrix:\n', S_B)

between-class Scatter Matrix:
 [[ 2.25 -3.  ]
 [-3.    4.  ]]


### Step 3: Solving the generalized eigenvalue problem for the matrix S−1WSB

In [184]:
eig_vals, eig_vecs = np.linalg.eig(np.linalg.inv(S_W).dot(S_B))

for i in range(len(eig_vals)):
    eigvec_sc = eig_vecs[:,i].reshape(2,1)   
    print('\nEigenvector {}: \n{}'.format(i+1, eigvec_sc.real))
    print('Eigenvalue {:}: {:}'.format(i+1, eig_vals[i].real))


Eigenvector 1: 
[[-0.8]
 [-0.6]]
Eigenvalue 1: 0.0

Eigenvector 2: 
[[ 0.5274]
 [-0.8496]]
Eigenvalue 2: 85.00000000000013


In [186]:
for i in range(len(eig_vals)):
    eigv = eig_vecs[:,i].reshape(2,1)
    np.testing.assert_array_almost_equal(np.linalg.inv(S_W).dot(S_B).dot(eigv),
                                         eig_vals[i] * eigv,
                                         decimal=6, err_msg='', verbose=True)
print('ok')

ok
